# MAT281 - Laboratorio N°02



<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$\displaystyle sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:
 * sma(2) = [promedio(1,2), promedio(2,3), promedio(3,4), promedio(4,5)] = [1.5, 2.5, 3.5, 4.5]


* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=3$ sería:
 * sma(3) = [promedio(1,2,3), promedio(2,3,4), promedio(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [17]:
# importar librerias
import numpy as np 

### Definir Función

In [77]:
def sma(A,n):
    x=[]
    if n>1:
        for i in range(len(A)-(n-1)):x.append(np.mean(A[i:i+n]))
    else:
        for i in range(len(A)-(n-1)):x.append(np.mean(A[i:i+1]))
    return np.array(x)  

In [61]:
# manera alternativa de funcion
def sma2(A,n):
    x=[]
    for i in range(len(A)-(n-1)):x.append(np.mean(A[i:i+n]))
    return np.array(x)        

### Preverificacion de ejemplos!!!

In [78]:
a = np.array([1,2,3,4,5])
print(sma(a, 1))

[1. 2. 3. 4. 5.]


In [73]:
a = np.array([1,2,3,4,5])
print(sma2(a, 1))

[1. 2. 3. 4. 5.]


### Verificar ejemplos

In [71]:
# ejemplo 01
a = np.array([1,2,3,4,5])

np.testing.assert_array_equal(
    sma(a, n=2),
    np.array([1.5, 2.5, 3.5, 4.5])
)

In [72]:
# ejemplo 02
a = np.array([5,3,8,10,2,1,5,1,0,2])

np.testing.assert_array_equal(
    sma(a, n=2),
    np.array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])
)

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,n,p)` cuyo input sea:
* $a$: un arreglo unidimensional, 
* $n$: el número de columnas,
* $p$: el número de pasos hacia adelante  

y retorne la matriz de $n$ columnas, cuyos desfaces hacia adelante se hacen de $p$ en $p$ pasos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


### Definir Función

In [38]:
def strides(a,n,p):
    b = np.empty(n) #sera actualizada pronto
    c = np.matrix([a[0:n]])  # primera fla agregada
    for i in range( 1, int((len(a)-n)/p)+1 ):  # c normaliza el stop donde saltara a la otra fila
        for j in range(n):
            b[j] = a[j + i*p]   #ordenar matrix
        c = np.vstack([c,b])
    return c

## Preverificacion de ejemplos

In [39]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
strides(a,4,2)

matrix([[ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  5.,  6.],
        [ 5.,  6.,  7.,  8.],
        [ 7.,  8.,  9., 10.]])

### Verificar ejemplos

In [40]:
# ejemplo 01
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
n=4
p=2

np.testing.assert_array_equal(
    strides(a,n,p),
    np.array([
       [ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]
    ])
)

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$\displaystyle M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

### Definir Función

In [41]:
def es_cudrado_magico(A):
    filas = np.apply_along_axis(sum, 0, A) #operacion suma con filas 
    columnas = np.apply_along_axis(sum, 1, A) #operaciones suma con columnas
    diago = np.trace(A)
    diago_2 = np.trace(np.fliplr(A))  # giro de matriz para tener la otra diag
    if len(np.unique(filas)) == len(np.unique(columnas)) == 1: #misma cantiadad?
        if filas[0] == columnas[0] == diago == diago_2:
            return True
    return False

In [28]:
def es_cuadrado_magico(A):
    max_num=A.shape[0]
    if A.shape[0] == A.shape[1]:
        print("es una matriz cuadrada")
        count=0
        for i in range(A.shape[0]):
            for j in range(A.shape[0]):
                count=count+A[i][j]
            if count == (max_num*(max_num**2+1))/2:
                count=0
                print(count)
            else: print('no es cuadrado magico')
     ###
    ### Falta terminar, solo evaluar funcion mas rapida de arriba hecha con full numpy
    

In [26]:
A = np.array([[4,9,2],[3,5,7],[8,1,6]])
es_cuadrado_magico(A)
A.shape[0]

es una matriz cuadrada


3

### Verificar ejemplos

In [42]:
# ejemplo 01
A = np.array([[4,9,2],[3,5,7],[8,1,6]])
assert es_cudrado_magico(A) == True, "ejemplo 01 incorrecto"

In [43]:
# ejemplo 02
B = np.array([[4,2,9],[3,5,7],[8,1,6]])
assert es_cudrado_magico(B) == False, "ejemplo 02 incorrecto"